apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wo2fkn4uz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wo2fkn4uz-go 
  name: wo2fkn4uz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wo2fkn4uz-go 
